// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_wrapper.proto

package Network;

public final class ServerWrapper {
  private ServerWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FrontEndTorrentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Network.FrontEndTorrent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string user = 2;</code>
     */
    java.lang.String getUser();
    /**
     * <code>string user = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>string group = 3;</code>
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 3;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code Network.FrontEndTorrent}
   */
  public  static final class FrontEndTorrent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Network.FrontEndTorrent)
      FrontEndTorrentOrBuilder {
    // Use FrontEndTorrent.newBuilder() to construct.
    private FrontEndTorrent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FrontEndTorrent() {
      id_ = "";
      user_ = "";
      group_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FrontEndTorrent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              user_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Network.ServerWrapper.internal_static_Network_FrontEndTorrent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Network.ServerWrapper.internal_static_Network_FrontEndTorrent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Network.ServerWrapper.FrontEndTorrent.class, Network.ServerWrapper.FrontEndTorrent.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    private volatile java.lang.Object user_;
    /**
     * <code>string user = 2;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <code>string user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 3;
    private volatile java.lang.Object group_;
    /**
     * <code>string group = 3;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 4;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, group_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, group_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Network.ServerWrapper.FrontEndTorrent)) {
        return super.equals(obj);
      }
      Network.ServerWrapper.FrontEndTorrent other = (Network.ServerWrapper.FrontEndTorrent) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getUser()
          .equals(other.getUser());
      result = result && getGroup()
          .equals(other.getGroup());
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Network.ServerWrapper.FrontEndTorrent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.FrontEndTorrent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Network.ServerWrapper.FrontEndTorrent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Network.FrontEndTorrent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Network.FrontEndTorrent)
        Network.ServerWrapper.FrontEndTorrentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Network.ServerWrapper.internal_static_Network_FrontEndTorrent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Network.ServerWrapper.internal_static_Network_FrontEndTorrent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Network.ServerWrapper.FrontEndTorrent.class, Network.ServerWrapper.FrontEndTorrent.Builder.class);
      }

      // Construct using Network.ServerWrapper.FrontEndTorrent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        user_ = "";

        group_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Network.ServerWrapper.internal_static_Network_FrontEndTorrent_descriptor;
      }

      public Network.ServerWrapper.FrontEndTorrent getDefaultInstanceForType() {
        return Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
      }

      public Network.ServerWrapper.FrontEndTorrent build() {
        Network.ServerWrapper.FrontEndTorrent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Network.ServerWrapper.FrontEndTorrent buildPartial() {
        Network.ServerWrapper.FrontEndTorrent result = new Network.ServerWrapper.FrontEndTorrent(this);
        result.id_ = id_;
        result.user_ = user_;
        result.group_ = group_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Network.ServerWrapper.FrontEndTorrent) {
          return mergeFrom((Network.ServerWrapper.FrontEndTorrent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Network.ServerWrapper.FrontEndTorrent other) {
        if (other == Network.ServerWrapper.FrontEndTorrent.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Network.ServerWrapper.FrontEndTorrent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Network.ServerWrapper.FrontEndTorrent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <code>string user = 2;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user = 2;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user = 2;</code>
       */
      public Builder clearUser() {
        
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>string user = 2;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 3;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 3;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 3;</code>
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 3;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 4;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Network.FrontEndTorrent)
    }

    // @@protoc_insertion_point(class_scope:Network.FrontEndTorrent)
    private static final Network.ServerWrapper.FrontEndTorrent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Network.ServerWrapper.FrontEndTorrent();
    }

    public static Network.ServerWrapper.FrontEndTorrent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FrontEndTorrent>
        PARSER = new com.google.protobuf.AbstractParser<FrontEndTorrent>() {
      public FrontEndTorrent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FrontEndTorrent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FrontEndTorrent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FrontEndTorrent> getParserForType() {
      return PARSER;
    }

    public Network.ServerWrapper.FrontEndTorrent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrackerTorrentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Network.TrackerTorrent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code Network.TrackerTorrent}
   */
  public  static final class TrackerTorrent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Network.TrackerTorrent)
      TrackerTorrentOrBuilder {
    // Use TrackerTorrent.newBuilder() to construct.
    private TrackerTorrent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrackerTorrent() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TrackerTorrent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Network.ServerWrapper.internal_static_Network_TrackerTorrent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Network.ServerWrapper.internal_static_Network_TrackerTorrent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Network.ServerWrapper.TrackerTorrent.class, Network.ServerWrapper.TrackerTorrent.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeBytes(1, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Network.ServerWrapper.TrackerTorrent)) {
        return super.equals(obj);
      }
      Network.ServerWrapper.TrackerTorrent other = (Network.ServerWrapper.TrackerTorrent) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Network.ServerWrapper.TrackerTorrent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.ServerWrapper.TrackerTorrent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.TrackerTorrent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.TrackerTorrent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Network.ServerWrapper.TrackerTorrent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Network.TrackerTorrent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Network.TrackerTorrent)
        Network.ServerWrapper.TrackerTorrentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Network.ServerWrapper.internal_static_Network_TrackerTorrent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Network.ServerWrapper.internal_static_Network_TrackerTorrent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Network.ServerWrapper.TrackerTorrent.class, Network.ServerWrapper.TrackerTorrent.Builder.class);
      }

      // Construct using Network.ServerWrapper.TrackerTorrent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Network.ServerWrapper.internal_static_Network_TrackerTorrent_descriptor;
      }

      public Network.ServerWrapper.TrackerTorrent getDefaultInstanceForType() {
        return Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
      }

      public Network.ServerWrapper.TrackerTorrent build() {
        Network.ServerWrapper.TrackerTorrent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Network.ServerWrapper.TrackerTorrent buildPartial() {
        Network.ServerWrapper.TrackerTorrent result = new Network.ServerWrapper.TrackerTorrent(this);
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Network.ServerWrapper.TrackerTorrent) {
          return mergeFrom((Network.ServerWrapper.TrackerTorrent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Network.ServerWrapper.TrackerTorrent other) {
        if (other == Network.ServerWrapper.TrackerTorrent.getDefaultInstance()) return this;
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Network.ServerWrapper.TrackerTorrent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Network.ServerWrapper.TrackerTorrent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Network.TrackerTorrent)
    }

    // @@protoc_insertion_point(class_scope:Network.TrackerTorrent)
    private static final Network.ServerWrapper.TrackerTorrent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Network.ServerWrapper.TrackerTorrent();
    }

    public static Network.ServerWrapper.TrackerTorrent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrackerTorrent>
        PARSER = new com.google.protobuf.AbstractParser<TrackerTorrent>() {
      public TrackerTorrent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TrackerTorrent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrackerTorrent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrackerTorrent> getParserForType() {
      return PARSER;
    }

    public Network.ServerWrapper.TrackerTorrent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Network.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    Network.ServerWrapper.FrontEndTorrent getFrontEndTorrent();
    /**
     * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    Network.ServerWrapper.FrontEndTorrentOrBuilder getFrontEndTorrentOrBuilder();

    /**
     * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
     */
    Network.ServerWrapper.TrackerTorrent getTrackerTorrent();
    /**
     * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
     */
    Network.ServerWrapper.TrackerTorrentOrBuilder getTrackerTorrentOrBuilder();

    public Network.ServerWrapper.ServerMessage.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code Network.ServerMessage}
   */
  public  static final class ServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Network.ServerMessage)
      ServerMessageOrBuilder {
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Network.ServerWrapper.FrontEndTorrent.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((Network.ServerWrapper.FrontEndTorrent) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(Network.ServerWrapper.FrontEndTorrent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Network.ServerWrapper.FrontEndTorrent) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              Network.ServerWrapper.TrackerTorrent.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((Network.ServerWrapper.TrackerTorrent) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(Network.ServerWrapper.TrackerTorrent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Network.ServerWrapper.TrackerTorrent) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Network.ServerWrapper.internal_static_Network_ServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Network.ServerWrapper.internal_static_Network_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Network.ServerWrapper.ServerMessage.class, Network.ServerWrapper.ServerMessage.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      FRONTENDTORRENT(1),
      TRACKERTORRENT(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return FRONTENDTORRENT;
          case 2: return TRACKERTORRENT;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int FRONTENDTORRENT_FIELD_NUMBER = 1;
    /**
     * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    public Network.ServerWrapper.FrontEndTorrent getFrontEndTorrent() {
      if (msgCase_ == 1) {
         return (Network.ServerWrapper.FrontEndTorrent) msg_;
      }
      return Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
    }
    /**
     * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    public Network.ServerWrapper.FrontEndTorrentOrBuilder getFrontEndTorrentOrBuilder() {
      if (msgCase_ == 1) {
         return (Network.ServerWrapper.FrontEndTorrent) msg_;
      }
      return Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
    }

    public static final int TRACKERTORRENT_FIELD_NUMBER = 2;
    /**
     * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
     */
    public Network.ServerWrapper.TrackerTorrent getTrackerTorrent() {
      if (msgCase_ == 2) {
         return (Network.ServerWrapper.TrackerTorrent) msg_;
      }
      return Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
    }
    /**
     * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
     */
    public Network.ServerWrapper.TrackerTorrentOrBuilder getTrackerTorrentOrBuilder() {
      if (msgCase_ == 2) {
         return (Network.ServerWrapper.TrackerTorrent) msg_;
      }
      return Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (Network.ServerWrapper.FrontEndTorrent) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (Network.ServerWrapper.TrackerTorrent) msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (Network.ServerWrapper.FrontEndTorrent) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Network.ServerWrapper.TrackerTorrent) msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Network.ServerWrapper.ServerMessage)) {
        return super.equals(obj);
      }
      Network.ServerWrapper.ServerMessage other = (Network.ServerWrapper.ServerMessage) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getFrontEndTorrent()
              .equals(other.getFrontEndTorrent());
          break;
        case 2:
          result = result && getTrackerTorrent()
              .equals(other.getTrackerTorrent());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + FRONTENDTORRENT_FIELD_NUMBER;
          hash = (53 * hash) + getFrontEndTorrent().hashCode();
          break;
        case 2:
          hash = (37 * hash) + TRACKERTORRENT_FIELD_NUMBER;
          hash = (53 * hash) + getTrackerTorrent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Network.ServerWrapper.ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.ServerWrapper.ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.ServerWrapper.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Network.ServerWrapper.ServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Network.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Network.ServerMessage)
        Network.ServerWrapper.ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Network.ServerWrapper.internal_static_Network_ServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Network.ServerWrapper.internal_static_Network_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Network.ServerWrapper.ServerMessage.class, Network.ServerWrapper.ServerMessage.Builder.class);
      }

      // Construct using Network.ServerWrapper.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Network.ServerWrapper.internal_static_Network_ServerMessage_descriptor;
      }

      public Network.ServerWrapper.ServerMessage getDefaultInstanceForType() {
        return Network.ServerWrapper.ServerMessage.getDefaultInstance();
      }

      public Network.ServerWrapper.ServerMessage build() {
        Network.ServerWrapper.ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Network.ServerWrapper.ServerMessage buildPartial() {
        Network.ServerWrapper.ServerMessage result = new Network.ServerWrapper.ServerMessage(this);
        if (msgCase_ == 1) {
          if (frontEndTorrentBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = frontEndTorrentBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (trackerTorrentBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = trackerTorrentBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Network.ServerWrapper.ServerMessage) {
          return mergeFrom((Network.ServerWrapper.ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Network.ServerWrapper.ServerMessage other) {
        if (other == Network.ServerWrapper.ServerMessage.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case FRONTENDTORRENT: {
            mergeFrontEndTorrent(other.getFrontEndTorrent());
            break;
          }
          case TRACKERTORRENT: {
            mergeTrackerTorrent(other.getTrackerTorrent());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Network.ServerWrapper.ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Network.ServerWrapper.ServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          Network.ServerWrapper.FrontEndTorrent, Network.ServerWrapper.FrontEndTorrent.Builder, Network.ServerWrapper.FrontEndTorrentOrBuilder> frontEndTorrentBuilder_;
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Network.ServerWrapper.FrontEndTorrent getFrontEndTorrent() {
        if (frontEndTorrentBuilder_ == null) {
          if (msgCase_ == 1) {
            return (Network.ServerWrapper.FrontEndTorrent) msg_;
          }
          return Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return frontEndTorrentBuilder_.getMessage();
          }
          return Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder setFrontEndTorrent(Network.ServerWrapper.FrontEndTorrent value) {
        if (frontEndTorrentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          frontEndTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder setFrontEndTorrent(
          Network.ServerWrapper.FrontEndTorrent.Builder builderForValue) {
        if (frontEndTorrentBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          frontEndTorrentBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder mergeFrontEndTorrent(Network.ServerWrapper.FrontEndTorrent value) {
        if (frontEndTorrentBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != Network.ServerWrapper.FrontEndTorrent.getDefaultInstance()) {
            msg_ = Network.ServerWrapper.FrontEndTorrent.newBuilder((Network.ServerWrapper.FrontEndTorrent) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            frontEndTorrentBuilder_.mergeFrom(value);
          }
          frontEndTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder clearFrontEndTorrent() {
        if (frontEndTorrentBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          frontEndTorrentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Network.ServerWrapper.FrontEndTorrent.Builder getFrontEndTorrentBuilder() {
        return getFrontEndTorrentFieldBuilder().getBuilder();
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Network.ServerWrapper.FrontEndTorrentOrBuilder getFrontEndTorrentOrBuilder() {
        if ((msgCase_ == 1) && (frontEndTorrentBuilder_ != null)) {
          return frontEndTorrentBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (Network.ServerWrapper.FrontEndTorrent) msg_;
          }
          return Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.Network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Network.ServerWrapper.FrontEndTorrent, Network.ServerWrapper.FrontEndTorrent.Builder, Network.ServerWrapper.FrontEndTorrentOrBuilder> 
          getFrontEndTorrentFieldBuilder() {
        if (frontEndTorrentBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = Network.ServerWrapper.FrontEndTorrent.getDefaultInstance();
          }
          frontEndTorrentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Network.ServerWrapper.FrontEndTorrent, Network.ServerWrapper.FrontEndTorrent.Builder, Network.ServerWrapper.FrontEndTorrentOrBuilder>(
                  (Network.ServerWrapper.FrontEndTorrent) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return frontEndTorrentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Network.ServerWrapper.TrackerTorrent, Network.ServerWrapper.TrackerTorrent.Builder, Network.ServerWrapper.TrackerTorrentOrBuilder> trackerTorrentBuilder_;
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Network.ServerWrapper.TrackerTorrent getTrackerTorrent() {
        if (trackerTorrentBuilder_ == null) {
          if (msgCase_ == 2) {
            return (Network.ServerWrapper.TrackerTorrent) msg_;
          }
          return Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return trackerTorrentBuilder_.getMessage();
          }
          return Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder setTrackerTorrent(Network.ServerWrapper.TrackerTorrent value) {
        if (trackerTorrentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          trackerTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder setTrackerTorrent(
          Network.ServerWrapper.TrackerTorrent.Builder builderForValue) {
        if (trackerTorrentBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          trackerTorrentBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder mergeTrackerTorrent(Network.ServerWrapper.TrackerTorrent value) {
        if (trackerTorrentBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != Network.ServerWrapper.TrackerTorrent.getDefaultInstance()) {
            msg_ = Network.ServerWrapper.TrackerTorrent.newBuilder((Network.ServerWrapper.TrackerTorrent) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            trackerTorrentBuilder_.mergeFrom(value);
          }
          trackerTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder clearTrackerTorrent() {
        if (trackerTorrentBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          trackerTorrentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Network.ServerWrapper.TrackerTorrent.Builder getTrackerTorrentBuilder() {
        return getTrackerTorrentFieldBuilder().getBuilder();
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Network.ServerWrapper.TrackerTorrentOrBuilder getTrackerTorrentOrBuilder() {
        if ((msgCase_ == 2) && (trackerTorrentBuilder_ != null)) {
          return trackerTorrentBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (Network.ServerWrapper.TrackerTorrent) msg_;
          }
          return Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.Network.TrackerTorrent trackerTorrent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Network.ServerWrapper.TrackerTorrent, Network.ServerWrapper.TrackerTorrent.Builder, Network.ServerWrapper.TrackerTorrentOrBuilder> 
          getTrackerTorrentFieldBuilder() {
        if (trackerTorrentBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = Network.ServerWrapper.TrackerTorrent.getDefaultInstance();
          }
          trackerTorrentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Network.ServerWrapper.TrackerTorrent, Network.ServerWrapper.TrackerTorrent.Builder, Network.ServerWrapper.TrackerTorrentOrBuilder>(
                  (Network.ServerWrapper.TrackerTorrent) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return trackerTorrentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Network.ServerMessage)
    }

    // @@protoc_insertion_point(class_scope:Network.ServerMessage)
    private static final Network.ServerWrapper.ServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Network.ServerWrapper.ServerMessage();
    }

    public static Network.ServerWrapper.ServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    public Network.ServerWrapper.ServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Network_FrontEndTorrent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Network_FrontEndTorrent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Network_TrackerTorrent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Network_TrackerTorrent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Network_ServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Network_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024server_wrapper.proto\022\007Network\"K\n\017Front" +
      "EndTorrent\022\n\n\002id\030\001 \001(\t\022\014\n\004user\030\002 \001(\t\022\r\n\005" +
      "group\030\003 \001(\t\022\017\n\007content\030\004 \001(\014\"!\n\016TrackerT" +
      "orrent\022\017\n\007content\030\001 \001(\014\"~\n\rServerMessage" +
      "\0223\n\017frontEndTorrent\030\001 \001(\0132\030.Network.Fron" +
      "tEndTorrentH\000\0221\n\016trackerTorrent\030\002 \001(\0132\027." +
      "Network.TrackerTorrentH\000B\005\n\003msgb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Network_FrontEndTorrent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Network_FrontEndTorrent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Network_FrontEndTorrent_descriptor,
        new java.lang.String[] { "Id", "User", "Group", "Content", });
    internal_static_Network_TrackerTorrent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Network_TrackerTorrent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Network_TrackerTorrent_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_Network_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Network_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Network_ServerMessage_descriptor,
        new java.lang.String[] { "FrontEndTorrent", "TrackerTorrent", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
