// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_wrapper.proto

package server_network;

public final class ServerWrapper {
  private ServerWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FrontEndTorrentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server_network.FrontEndTorrent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string user = 2;</code>
     */
    String getUser();
    /**
     * <code>string user = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>string group = 3;</code>
     */
    String getGroup();
    /**
     * <code>string group = 3;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code server_network.FrontEndTorrent}
   */
  public  static final class FrontEndTorrent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server_network.FrontEndTorrent)
      FrontEndTorrentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FrontEndTorrent.newBuilder() to construct.
    private FrontEndTorrent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FrontEndTorrent() {
      id_ = "";
      user_ = "";
      group_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FrontEndTorrent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              user_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerWrapper.internal_static_server_network_FrontEndTorrent_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerWrapper.internal_static_server_network_FrontEndTorrent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FrontEndTorrent.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    private volatile Object user_;
    /**
     * <code>string user = 2;</code>
     */
    public String getUser() {
      Object ref = user_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <code>string user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 3;
    private volatile Object group_;
    /**
     * <code>string group = 3;</code>
     */
    public String getGroup() {
      Object ref = group_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 4;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, group_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, group_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FrontEndTorrent)) {
        return super.equals(obj);
      }
      FrontEndTorrent other = (FrontEndTorrent) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getUser()
          .equals(other.getUser());
      result = result && getGroup()
          .equals(other.getGroup());
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FrontEndTorrent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEndTorrent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEndTorrent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEndTorrent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEndTorrent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrontEndTorrent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrontEndTorrent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEndTorrent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEndTorrent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FrontEndTorrent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrontEndTorrent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrontEndTorrent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FrontEndTorrent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server_network.FrontEndTorrent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server_network.FrontEndTorrent)
        FrontEndTorrentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerWrapper.internal_static_server_network_FrontEndTorrent_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerWrapper.internal_static_server_network_FrontEndTorrent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FrontEndTorrent.class, Builder.class);
      }

      // Construct using server_network.ServerWrapper.FrontEndTorrent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        user_ = "";

        group_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerWrapper.internal_static_server_network_FrontEndTorrent_descriptor;
      }

      public FrontEndTorrent getDefaultInstanceForType() {
        return FrontEndTorrent.getDefaultInstance();
      }

      public FrontEndTorrent build() {
        FrontEndTorrent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FrontEndTorrent buildPartial() {
        FrontEndTorrent result = new FrontEndTorrent(this);
        result.id_ = id_;
        result.user_ = user_;
        result.group_ = group_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FrontEndTorrent) {
          return mergeFrom((FrontEndTorrent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FrontEndTorrent other) {
        if (other == FrontEndTorrent.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FrontEndTorrent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FrontEndTorrent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object user_ = "";
      /**
       * <code>string user = 2;</code>
       */
      public String getUser() {
        Object ref = user_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user = 2;</code>
       */
      public Builder setUser(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user = 2;</code>
       */
      public Builder clearUser() {
        
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>string user = 2;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        user_ = value;
        onChanged();
        return this;
      }

      private Object group_ = "";
      /**
       * <code>string group = 3;</code>
       */
      public String getGroup() {
        Object ref = group_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string group = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 3;</code>
       */
      public Builder setGroup(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 3;</code>
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 3;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 4;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server_network.FrontEndTorrent)
    }

    // @@protoc_insertion_point(class_scope:server_network.FrontEndTorrent)
    private static final FrontEndTorrent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FrontEndTorrent();
    }

    public static FrontEndTorrent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FrontEndTorrent>
        PARSER = new com.google.protobuf.AbstractParser<FrontEndTorrent>() {
      public FrontEndTorrent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FrontEndTorrent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FrontEndTorrent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FrontEndTorrent> getParserForType() {
      return PARSER;
    }

    public FrontEndTorrent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrackerTorrentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server_network.TrackerTorrent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code server_network.TrackerTorrent}
   */
  public  static final class TrackerTorrent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server_network.TrackerTorrent)
      TrackerTorrentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrackerTorrent.newBuilder() to construct.
    private TrackerTorrent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrackerTorrent() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrackerTorrent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerWrapper.internal_static_server_network_TrackerTorrent_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerWrapper.internal_static_server_network_TrackerTorrent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TrackerTorrent.class, Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeBytes(1, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TrackerTorrent)) {
        return super.equals(obj);
      }
      TrackerTorrent other = (TrackerTorrent) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TrackerTorrent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrackerTorrent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrackerTorrent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrackerTorrent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrackerTorrent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TrackerTorrent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TrackerTorrent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TrackerTorrent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TrackerTorrent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TrackerTorrent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TrackerTorrent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TrackerTorrent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TrackerTorrent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server_network.TrackerTorrent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server_network.TrackerTorrent)
        TrackerTorrentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerWrapper.internal_static_server_network_TrackerTorrent_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerWrapper.internal_static_server_network_TrackerTorrent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TrackerTorrent.class, Builder.class);
      }

      // Construct using server_network.ServerWrapper.TrackerTorrent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerWrapper.internal_static_server_network_TrackerTorrent_descriptor;
      }

      public TrackerTorrent getDefaultInstanceForType() {
        return TrackerTorrent.getDefaultInstance();
      }

      public TrackerTorrent build() {
        TrackerTorrent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TrackerTorrent buildPartial() {
        TrackerTorrent result = new TrackerTorrent(this);
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TrackerTorrent) {
          return mergeFrom((TrackerTorrent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TrackerTorrent other) {
        if (other == TrackerTorrent.getDefaultInstance()) return this;
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TrackerTorrent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TrackerTorrent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server_network.TrackerTorrent)
    }

    // @@protoc_insertion_point(class_scope:server_network.TrackerTorrent)
    private static final TrackerTorrent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TrackerTorrent();
    }

    public static TrackerTorrent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrackerTorrent>
        PARSER = new com.google.protobuf.AbstractParser<TrackerTorrent>() {
      public TrackerTorrent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TrackerTorrent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrackerTorrent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TrackerTorrent> getParserForType() {
      return PARSER;
    }

    public TrackerTorrent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server_network.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    boolean hasFrontEndTorrent();
    /**
     * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    FrontEndTorrent getFrontEndTorrent();
    /**
     * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    FrontEndTorrentOrBuilder getFrontEndTorrentOrBuilder();

    /**
     * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
     */
    boolean hasTrackerTorrent();
    /**
     * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
     */
    TrackerTorrent getTrackerTorrent();
    /**
     * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
     */
    TrackerTorrentOrBuilder getTrackerTorrentOrBuilder();

    public ServerMessage.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code server_network.ServerMessage}
   */
  public  static final class ServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server_network.ServerMessage)
      ServerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMessage() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              FrontEndTorrent.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((FrontEndTorrent) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(FrontEndTorrent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((FrontEndTorrent) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              TrackerTorrent.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((TrackerTorrent) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(TrackerTorrent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((TrackerTorrent) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerWrapper.internal_static_server_network_ServerMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerWrapper.internal_static_server_network_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerMessage.class, Builder.class);
    }

    private int msgCase_ = 0;
    private Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      FRONTENDTORRENT(1),
      TRACKERTORRENT(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return FRONTENDTORRENT;
          case 2: return TRACKERTORRENT;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int FRONTENDTORRENT_FIELD_NUMBER = 1;
    /**
     * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    public boolean hasFrontEndTorrent() {
      return msgCase_ == 1;
    }
    /**
     * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    public FrontEndTorrent getFrontEndTorrent() {
      if (msgCase_ == 1) {
         return (FrontEndTorrent) msg_;
      }
      return FrontEndTorrent.getDefaultInstance();
    }
    /**
     * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
     */
    public FrontEndTorrentOrBuilder getFrontEndTorrentOrBuilder() {
      if (msgCase_ == 1) {
         return (FrontEndTorrent) msg_;
      }
      return FrontEndTorrent.getDefaultInstance();
    }

    public static final int TRACKERTORRENT_FIELD_NUMBER = 2;
    /**
     * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
     */
    public boolean hasTrackerTorrent() {
      return msgCase_ == 2;
    }
    /**
     * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
     */
    public TrackerTorrent getTrackerTorrent() {
      if (msgCase_ == 2) {
         return (TrackerTorrent) msg_;
      }
      return TrackerTorrent.getDefaultInstance();
    }
    /**
     * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
     */
    public TrackerTorrentOrBuilder getTrackerTorrentOrBuilder() {
      if (msgCase_ == 2) {
         return (TrackerTorrent) msg_;
      }
      return TrackerTorrent.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (FrontEndTorrent) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (TrackerTorrent) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (FrontEndTorrent) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (TrackerTorrent) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServerMessage)) {
        return super.equals(obj);
      }
      ServerMessage other = (ServerMessage) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getFrontEndTorrent()
              .equals(other.getFrontEndTorrent());
          break;
        case 2:
          result = result && getTrackerTorrent()
              .equals(other.getTrackerTorrent());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + FRONTENDTORRENT_FIELD_NUMBER;
          hash = (53 * hash) + getFrontEndTorrent().hashCode();
          break;
        case 2:
          hash = (37 * hash) + TRACKERTORRENT_FIELD_NUMBER;
          hash = (53 * hash) + getTrackerTorrent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server_network.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server_network.ServerMessage)
        ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerWrapper.internal_static_server_network_ServerMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerWrapper.internal_static_server_network_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerMessage.class, Builder.class);
      }

      // Construct using server_network.ServerWrapper.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerWrapper.internal_static_server_network_ServerMessage_descriptor;
      }

      public ServerMessage getDefaultInstanceForType() {
        return ServerMessage.getDefaultInstance();
      }

      public ServerMessage build() {
        ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerMessage buildPartial() {
        ServerMessage result = new ServerMessage(this);
        if (msgCase_ == 1) {
          if (frontEndTorrentBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = frontEndTorrentBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (trackerTorrentBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = trackerTorrentBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerMessage) {
          return mergeFrom((ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerMessage other) {
        if (other == ServerMessage.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case FRONTENDTORRENT: {
            mergeFrontEndTorrent(other.getFrontEndTorrent());
            break;
          }
          case TRACKERTORRENT: {
            mergeTrackerTorrent(other.getTrackerTorrent());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEndTorrent, FrontEndTorrent.Builder, FrontEndTorrentOrBuilder> frontEndTorrentBuilder_;
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public boolean hasFrontEndTorrent() {
        return msgCase_ == 1;
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public FrontEndTorrent getFrontEndTorrent() {
        if (frontEndTorrentBuilder_ == null) {
          if (msgCase_ == 1) {
            return (FrontEndTorrent) msg_;
          }
          return FrontEndTorrent.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return frontEndTorrentBuilder_.getMessage();
          }
          return FrontEndTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder setFrontEndTorrent(FrontEndTorrent value) {
        if (frontEndTorrentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          frontEndTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder setFrontEndTorrent(
          FrontEndTorrent.Builder builderForValue) {
        if (frontEndTorrentBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          frontEndTorrentBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder mergeFrontEndTorrent(FrontEndTorrent value) {
        if (frontEndTorrentBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != FrontEndTorrent.getDefaultInstance()) {
            msg_ = FrontEndTorrent.newBuilder((FrontEndTorrent) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            frontEndTorrentBuilder_.mergeFrom(value);
          }
          frontEndTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public Builder clearFrontEndTorrent() {
        if (frontEndTorrentBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          frontEndTorrentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public FrontEndTorrent.Builder getFrontEndTorrentBuilder() {
        return getFrontEndTorrentFieldBuilder().getBuilder();
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      public FrontEndTorrentOrBuilder getFrontEndTorrentOrBuilder() {
        if ((msgCase_ == 1) && (frontEndTorrentBuilder_ != null)) {
          return frontEndTorrentBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (FrontEndTorrent) msg_;
          }
          return FrontEndTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.server_network.FrontEndTorrent frontEndTorrent = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FrontEndTorrent, FrontEndTorrent.Builder, FrontEndTorrentOrBuilder>
          getFrontEndTorrentFieldBuilder() {
        if (frontEndTorrentBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = FrontEndTorrent.getDefaultInstance();
          }
          frontEndTorrentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FrontEndTorrent, FrontEndTorrent.Builder, FrontEndTorrentOrBuilder>(
                  (FrontEndTorrent) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return frontEndTorrentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          TrackerTorrent, TrackerTorrent.Builder, TrackerTorrentOrBuilder> trackerTorrentBuilder_;
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public boolean hasTrackerTorrent() {
        return msgCase_ == 2;
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public TrackerTorrent getTrackerTorrent() {
        if (trackerTorrentBuilder_ == null) {
          if (msgCase_ == 2) {
            return (TrackerTorrent) msg_;
          }
          return TrackerTorrent.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return trackerTorrentBuilder_.getMessage();
          }
          return TrackerTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder setTrackerTorrent(TrackerTorrent value) {
        if (trackerTorrentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          trackerTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder setTrackerTorrent(
          TrackerTorrent.Builder builderForValue) {
        if (trackerTorrentBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          trackerTorrentBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder mergeTrackerTorrent(TrackerTorrent value) {
        if (trackerTorrentBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != TrackerTorrent.getDefaultInstance()) {
            msg_ = TrackerTorrent.newBuilder((TrackerTorrent) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            trackerTorrentBuilder_.mergeFrom(value);
          }
          trackerTorrentBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public Builder clearTrackerTorrent() {
        if (trackerTorrentBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          trackerTorrentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public TrackerTorrent.Builder getTrackerTorrentBuilder() {
        return getTrackerTorrentFieldBuilder().getBuilder();
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      public TrackerTorrentOrBuilder getTrackerTorrentOrBuilder() {
        if ((msgCase_ == 2) && (trackerTorrentBuilder_ != null)) {
          return trackerTorrentBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (TrackerTorrent) msg_;
          }
          return TrackerTorrent.getDefaultInstance();
        }
      }
      /**
       * <code>.server_network.TrackerTorrent trackerTorrent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TrackerTorrent, TrackerTorrent.Builder, TrackerTorrentOrBuilder>
          getTrackerTorrentFieldBuilder() {
        if (trackerTorrentBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = TrackerTorrent.getDefaultInstance();
          }
          trackerTorrentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TrackerTorrent, TrackerTorrent.Builder, TrackerTorrentOrBuilder>(
                  (TrackerTorrent) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return trackerTorrentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server_network.ServerMessage)
    }

    // @@protoc_insertion_point(class_scope:server_network.ServerMessage)
    private static final ServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerMessage();
    }

    public static ServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    public ServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_network_FrontEndTorrent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_network_FrontEndTorrent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_network_TrackerTorrent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_network_TrackerTorrent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_network_ServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_network_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024server_wrapper.proto\022\016server_network\"K" +
      "\n\017FrontEndTorrent\022\n\n\002id\030\001 \001(\t\022\014\n\004user\030\002 " +
      "\001(\t\022\r\n\005group\030\003 \001(\t\022\017\n\007content\030\004 \001(\014\"!\n\016T" +
      "rackerTorrent\022\017\n\007content\030\001 \001(\014\"\214\001\n\rServe" +
      "rMessage\022:\n\017frontEndTorrent\030\001 \001(\0132\037.serv" +
      "er_network.FrontEndTorrentH\000\0228\n\016trackerT" +
      "orrent\030\002 \001(\0132\036.server_network.TrackerTor" +
      "rentH\000B\005\n\003msgb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_network_FrontEndTorrent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_network_FrontEndTorrent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_network_FrontEndTorrent_descriptor,
        new String[] { "Id", "User", "Group", "Content", });
    internal_static_server_network_TrackerTorrent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_network_TrackerTorrent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_network_TrackerTorrent_descriptor,
        new String[] { "Content", });
    internal_static_server_network_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_network_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_network_ServerMessage_descriptor,
        new String[] { "FrontEndTorrent", "TrackerTorrent", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
