%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(account).
-define(account, true).

-define(account_gpb_version, "4.1.1").

-ifndef('ACCOUNT_PB_H').
-define('ACCOUNT_PB_H', true).
-record('Account',
        {type = false           :: boolean() | 0 | 1 | undefined, % = 1
         username = <<>>        :: iodata() | undefined, % = 2
         password = <<>>        :: iodata() | undefined, % = 3
         name = <<>>            :: iodata() | undefined % = 4
        }).
-endif.

-endif.
