%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef('Account').
-define('Account', true).

-define('Account_gpb_version', "4.1.1").

-ifndef('ACCOUNT_PB_H').
-define('ACCOUNT_PB_H', true).
-record('Account',
        {type                   :: boolean() | 0 | 1, % = 1
         username               :: iodata(),        % = 2
         password               :: iodata(),        % = 3
         name                   :: iodata()         % = 3
        }).
-endif.

-endif.
