%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(server_wrapper).
-define(server_wrapper, true).

-define(server_wrapper_gpb_version, "4.1.1").

-ifndef('TRACKERTORRENT_PB_H').
-define('TRACKERTORRENT_PB_H', true).
-record('TrackerTorrent',
        {group = <<>>           :: iodata() | undefined, % = 1
         content = <<>>         :: binary() | undefined % = 2
        }).
-endif.

-ifndef('FRONTENDTORRENT_PB_H').
-define('FRONTENDTORRENT_PB_H', true).
-record('FrontEndTorrent',
        {id = <<>>              :: iodata() | undefined, % = 1
         user = <<>>            :: iodata() | undefined, % = 2
         group = <<>>           :: iodata() | undefined, % = 3
         content = <<>>         :: binary() | undefined % = 4
        }).
-endif.

-ifndef('SERVERMESSAGE_PB_H').
-define('SERVERMESSAGE_PB_H', true).
-record('ServerMessage',
        {msg                    :: {frontEndTorrent, #'FrontEndTorrent'{}} | {trackerTorrent, #'TrackerTorrent'{}} | undefined % oneof
        }).
-endif.

-endif.
