%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(torrentWrapper).
-define(torrentWrapper, true).

-define(torrentWrapper_gpb_version, "4.1.1").

-ifndef('TORRENTWRAPPER_PB_H').
-define('TORRENTWRAPPER_PB_H', true).
-record('TorrentWrapper',
        {group = <<>>           :: iodata() | undefined, % = 1
         content = <<>>         :: binary() | undefined % = 2
        }).
-endif.

-endif.
