#!/bin/bash
zk-server-1/bin/zkServer.sh start
zk-server-2/bin/zkServer.sh start
zk-server-3/bin/zkServer.sh start
zk-server-1/bin/zkServer.sh status
zk-server-2/bin/zkServer.sh status
zk-server-3/bin/zkServer.sh status
gnome-terminal -e "zk-server-1/bin/zkCli.sh -server 127.0.0.1:2182"
gnome-terminal -e "zk-server-2/bin/zkCli.sh -server 127.0.0.1:2183"
gnome-terminal -e "zk-server-3/bin/zkCli.sh -server 127.0.0.1:2184"